version: "3.9"
services:
  nginx:
    image: nginx:latest
    container_name: nginx-proxy
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - aplicacion_monolitica
  postgresql-db:
    image: postgres
    restart: always
    volumes:
      - ./data/db:/var/lib/postgresql
    environment:
      POSTGRES_PASSWORD: shinis
      POSTGRES_DB: Monolitica
    ports:
      - 5432:5432

  aplicacion_monolitica:
    container_name: aplicacion_monolitica
    image: dhorol/aplicacion_monolitica
    ports:
      - "8091:8090"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgresql-db:5432/Monolitica?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true&useSSL=false
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=shinis
    deploy:
      restart_policy:
        condition: on-failure
    depends_on:
      - postgresql-db

